"""NSState: full state of a nested sampling run.

Carries the live walker population (as a batched MCState), the
log-evidence accumulator, an iteration counter, and RNG state. Registered
as a JAX pytree for compatibility with JIT/vmap.

Dead points are *not* on NSState — the algorithm never reads them, only
emits them via ``ns_step``'s ``info`` dict at cull time, so they don't
belong on the state.  Per-iteration callbacks (``EnergyLogger``,
``TrajectoryCallback``) consume ``info["dead_walker"]`` (a ``WalkerState``
pytree) and persist the values straight to disk — there is no in-memory
dead-point buffer.

NSState is ensemble-agnostic — it doesn't know about pressure, chemical
potentials, or ensemble type. The full ensemble potential is stored in
MCState.energy (via EnsembleBackend), and ns_step reads it directly.
"""

from __future__ import annotations

import dataclasses
from collections.abc import Sequence
from typing import Any

import jax
import jax.numpy as jnp
from jaxtyping import Array, Float, Int, Key

from jaxrens.state.walker import static_field


def _ns_flatten(state: NSState) -> tuple[list, dict]:
    leaves = []
    aux = {}
    for f in dataclasses.fields(state):
        val = getattr(state, f.name)
        if f.metadata.get("static", False):
            aux[f.name] = val
        else:
            leaves.append(val)
    return leaves, aux


def _ns_unflatten(aux: dict, leaves: Sequence[Any]) -> NSState:
    fields = dataclasses.fields(NSState)
    dynamic_fields = [f for f in fields if not f.metadata.get("static", False)]
    kwargs = dict(aux)
    for f, val in zip(dynamic_fields, leaves):
        kwargs[f.name] = val
    return NSState(**kwargs)


@dataclasses.dataclass
class NSState:
    """Algorithm-only state of a nested sampling run.

    Ensemble-agnostic: MCState.energy is the full potential (U, H, Ω, ...),
    computed by the backend (possibly wrapped in EnsembleBackend).

    Shape annotations use a variadic batch prefix ``*B`` to cover all three
    BatchDescriptor topologies: SingleRun (``*B = ()``), VmapRuns
    (``*B = (n_runs,)``), and PmapVmapRuns (``*B = (G, P)``).

    Attributes:
        population: Batched MCState with shape ``(*B, n_walkers, ...)`` on
            every field.  Typed ``Any`` because ``MCState`` is generated by a
            factory in ``state/mc_state.py`` and not statically named.
        log_evidence: Running log-evidence estimate, shape ``(*B,)``.
        iteration: Current iteration count, shape ``(*B,)``.  Used inside
            JIT for the prior-mass weight in log_evidence accumulation.
        emax: Per-replica NS contour, shape ``(*B,)`` — the constraint
            level the most recently completed ``ns_step`` culled at.
            Algorithm state, NOT a derived quantity: it is set by
            ``ns_step`` (and ``ns_step_sharded``) at cull time and read
            verbatim by ``adapt_step`` and replica-exchange, neither of
            which re-derive it from ``population.energy``.  This
            separation matters because ``population.energy`` is just
            *empirical samples* from the likelihood-restricted prior
            parameterised by ``emax``; collapsing the two via
            ``max(pop.energy)`` conflates the distribution's defining
            parameter with a sample statistic and lets post-MCMC noise
            (or future pop-mutators) silently shift the contour.  Init
            value is ``+inf`` (no contour enforced yet — the first
            ``ns_step`` defines ``L_0``).
        rng_key: JAX PRNG key array, shape ``(*B,)``.
        n_walkers: Number of live walkers (compile-time constant).
        n_atoms: Number of atoms (compile-time constant).
    """

    # Walker population — batched MCState, (*B, n_walkers, ...) on every field
    population: Any  # MCState instance (dynamic pytree)

    # NS bookkeeping
    log_evidence: Float[Array, "*B"]
    iteration: Int[Array, "*B"]
    emax: Float[Array, "*B"]
    rng_key: Key[Array, "*B"]

    # Compile-time constants
    n_walkers: int = static_field(default=0)
    n_atoms: int = static_field(default=0)

    def set(self, **kwargs: Any) -> NSState:
        return dataclasses.replace(self, **kwargs)


jax.tree_util.register_pytree_node(
    NSState,
    _ns_flatten,
    _ns_unflatten,
)
